# pyright: standard
import argparse
import json
import pickle
import shutil
import subprocess
import sys
from pathlib import Path

import _pre_init
from rich import print

from src.models.manim import SimulationRecord

SCENE_SCRIPT = _pre_init.PROJECT_ROOT / "scripts/scene.py"


def find_latest_pkl() -> Path:
    outputs = _pre_init.PROJECT_ROOT / "outputs"

    pkl_files = list(outputs.rglob("bounce_history.pkl"))

    if not pkl_files:
        raise FileNotFoundError(f"No .pkl files found in {outputs}")

    # 按修改时间排序，取最新
    return max(pkl_files, key=lambda p: p.stat().st_mtime)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", type=Path, help="Path to the input pkl file")
    parser.add_argument("--ball_color", type=str, default="BLUE")
    parser.add_argument("--border_color", type=str, default="GREY")
    parser.add_argument("--size", type=int, default=960, help="Pixel size of the rendered video")
    parser.add_argument("--fps", "--frame_rate", type=int, default=30, help="Frame rate of the rendered video")
    args, unknown = parser.parse_known_args()

    pkl_file = find_latest_pkl() if args.input is None else args.input
    config_data = {
        "_comment": "This is a dynamic configuration file generated by `scripts/render_ball.py`",
        "pkl_file": pkl_file.as_posix(),
        "ball_color": args.ball_color,
        "border_color": args.border_color,
    }
    with open(_pre_init.PROJECT_ROOT / "scripts/config.tmp.json", "w", encoding="utf-8") as f:
        json.dump(config_data, f, indent=2)

    with open(pkl_file, "rb") as f:
        record: SimulationRecord = pickle.load(f)

    sys.argv = [sys.argv[0]] + unknown
    output_file = (
        _pre_init.PROJECT_ROOT
        / f"manim-videos"
        / f"{Path(record.meta.midi_file).stem}-{record.meta.inst_idx}"
        / f"{args.size}p{args.fps}.mp4"
    )
    output_file.parent.mkdir(parents=True, exist_ok=True)
    if pkl_file.resolve() == output_file.with_suffix(".pkl").resolve():
        pass
    else:
        shutil.copy2(pkl_file, output_file.with_suffix(".pkl"))

    manim_cmd = (
        ["manim"]
        + [SCENE_SCRIPT.as_posix(), "BouncingBallScene"]
        + unknown
        + ["--resolution", f"{args.size},{args.size}"]
        + ["--fps", str(args.fps)]
        + ["--output_file", output_file.as_posix()]
    )
    print(f"Running command: '{" ".join(manim_cmd)}'")
    subprocess.run(manim_cmd)
