# pyright: standard
import argparse
import json
import os
import pickle
import subprocess
import sys
from pathlib import Path

import _pre_init
from rich import print

from src.midi import midi_tracks_to_wav
from src.models.manim import SimulationRecord


def find_latest_pkl() -> Path:
    outputs = _pre_init.PROJECT_ROOT / "outputs"

    pkl_files = list(outputs.rglob("bounce_history.pkl"))

    if not pkl_files:
        raise FileNotFoundError(f"No .pkl files found in {outputs}")

    # 按修改时间排序，取最新
    return max(pkl_files, key=lambda p: p.stat().st_mtime)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--ball_color", type=str, default="BLUE")
    parser.add_argument("--border_color", type=str, default="GREY")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--manim", action="store_true", help="Use manim command")
    group.add_argument("--ffmpeg", action="store_true", help="Use ffmpeg command")
    args, unknown = parser.parse_known_args()

    pkl_file = find_latest_pkl()
    config_data = {
        "_comment": "This is a dynamic configuration file generated by `scripts/render_ball.py`",
        "pkl_file": pkl_file.as_posix(),
        "ball_color": args.ball_color,
        "border_color": args.border_color,
    }
    with open(_pre_init.PROJECT_ROOT / "scripts/config.tmp.json", "w", encoding="utf-8") as f:
        json.dump(config_data, f, indent=2)
    with open(pkl_file, "rb") as f:
        record: SimulationRecord = pickle.load(f)

    midi_file = Path(record.meta.midi_file)
    midi_tracks_to_wav(midi_file, [0], wav_output_path=_pre_init.ASSETS_PATH / "wav")

    sys.argv = [sys.argv[0]] + unknown
    manim_cmd = [
        "manim",
        (_pre_init.PROJECT_ROOT / "scripts/scene.py").as_posix(),
        "BouncingBallScene",
    ] + unknown

    print(record.collisions[0].time)
    offset_ms = int(record.collisions[0].time * 1000)

    ffmpeg_cmd = [
        "ffmpeg",
        "-i",
        r"C:\_\bounce-music-py\media\videos\scene\1080p15\BouncingBallScene.mp4",
        "-i",
        r"C:\_\bounce-music-py\assets\wav\春日影-My GO_爱给网_aigei_com_0.wav",
        "-filter_complex",
        f"[1:a]adelay={offset_ms}[a1]",
        "-map",
        "0:v",
        "-map",
        "[a1]",
        "-c:v",
        "copy",
        "-c:a",
        "aac",
        "-strict",
        "experimental",
        "output.mp4",
        "-y",
    ]

    print(f"Running command: '{" ".join(manim_cmd)}'")
    if args.manim:
        subprocess.run(manim_cmd)
    if args.ffmpeg:
        subprocess.run(ffmpeg_cmd)
